import { Space_Mono } from 'next/font/google'
import './globals.css'

const spaceMono = Space_Mono({
  variable: '--font-space',
  subsets: ['latin'],
  weight: '400',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html
      lang="pt-BR"
      className={`${spaceMono.variable} h-full antialiased scroll-smooth`}
    >
      <body className="min-h-full flex flex-col h-[5000px]">
        <main className="cyber-bg">
          <div className="glow-purple" />

          <div className="cyber-grid" />
          <div className="cyber-noise" />
          <div className="cyber-vignette" />

          {children}
        </main>
      </body>
    </html>
  )
}
